unstable_features = true
combine_control_expr = false
comment_width = 0
wrap_comments = false
fn_single_line = true
format_strings = true
max_width = 79
newline_style = "Unix"
normalize_comments = true
use_try_shorthand = true
group_imports = "StdExternalCrate"
merge_imports = true
