name: Build and release bot

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Make release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/knifebot"
          token: ${{ secrets.GITHUB_TOKEN }}
